# Generated by Django 3.1.7 on 2021-03-03 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Введите никнейм нового пользователя', max_length=64, unique=True, verbose_name='Никнейм')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Фамилия пользователя')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthday_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-published'],
            },
        ),
    ]
